import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Navbar from '@/components/Navbar'
import { NextAuthProvider } from '@/components/Providers'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>
//         {/* <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
//         {/* <body className={inter.className}> */}
//         {/* //mx는 좌우의 마진을 자동으로 넣는다 */}
//         <NextAuthProvider>
//           <div className="max-w-3xl mx-auto p-4">
//             <Navbar />
//             <div className="mt-8">{children}</div>
//           </div>
//         </NextAuthProvider>
//       </body>
//       {/* </body> */}
//     </html>
//   )
// }
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthProvider>
          <div className="max-w-4xl mx-auto ">
            <Navbar />
            <div className="mt-8">{children}</div>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  )
}
